apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadrift
spec:
  template:
    spec:
      containers:
      - name: datadrift
        image: quay.io/datadrift/data-drift:0.0.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: private-key
              key: private-key.pem
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              name: datadrift-secrets
              key: GITHUB_APP_ID
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi