apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadrift
spec:
  template:
    spec:
      containers:
      - name: datadrift
        image: registry/datadrift:tag
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: GITHUB_TOKEN
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi