commonLabels:
  app: datadrift

namespace: my-k8s-namespace

resources:
- service.yaml
- deployment.yaml
- ingress.yaml

secretGenerator:
- name: github-app-private-key
  envs:
  - .env.secret
- name: github-app-id
  envs:
  - .env.secret