name: Data-Drift Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t quay.io/datadrift/driftdb:${{ steps.date.outputs.date }} -t quay.io/datadrift/driftdb:latest .

      - name: Login to Quay.io
        run: docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}

      - name: Push Docker image
        run: docker push quay.io/datadrift/driftdb:${{ steps.date.outputs.date }}
