name: Driftdb Tests

on:
  push:
    branches:
      - main
      - "ci/*"
    paths:
      - "tools/driftdb/**"
  pull_request:
    paths:
      - "tools/driftdb/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/driftdb

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Run Mypy
        run: mypy --install-types --non-interactive driftdb
